### ISSUE TITLE
Streams leak memory

### ISSUE THREAD

**Issue by KennethL** [tsloughter/grpcbox#36]
grpcbox version v0.11.0
The grpcbox library leaks memory for each message sent on an open stream. In the `stream_state` record used for the `h2_stream gen_statem` data, there is an `incoming_frames` field. This field is a queue to which frames are added, but none are ever removed. In fact the information in this field is not used, apart from adding to it. Because of adding more and more data to it, the memory usage will keep increasing as long as the stream stays open. Note that currently the chatterbox library used by grpcbox is a forked one, not the original one.

**Comment by tsloughter** [comment]
Quick note on here about chatterbox fork. I haven't merged my changed into upstream chatterbox because I want full reviews of any change and those have been hard to come by, https://github.com/joedevivo/chatterbox/pull/127

If I could get help with reviewing it'll make upstreaming (I have permissions to merge into the main chatterbox repo) quicker.

**Comment by tsloughter** [comment]
It looks like this setup "works fine" for certain usages, like using http2 as http1.1 where you just do a request and then read a response when the stream ends -- so should also be fine for unary grpc calls?

I'm going to do a quick fix where the stream is just told to not store the response  since it doesn't need to when streaming data back to the client right now.
