### ISSUE TITLE
Missing trailers when streaming long data

### ISSUE THREAD

**Issue by russagit** [tsloughter/grpcbox#63]
I need to stream out some binary data following trailers like this:
```
...
grpcbox_stream:send(#{binary => Bin}, GRPCStream),
grpcbox_stream:add_trailers([{<<"size">>, integer_to_binary(byte_size(Bin))}], GRPCStream),
ok.
```
If the Bin is relatively small everything is ok. But if the Bin is big, then trailers are missed completely, in tcpdump I see that _end stream_ flag is send together with the last chunk of the binary. When testing with grpcurl it claims: "Message: server closed the stream without sending trailers"
It looks like the reason is here:
https://github.com/tsloughter/grpcbox/blob/main/src/grpcbox_stream.erl#L337
If I change send_end_stream to false the problem disappears.

**Comment by tsloughter** [comment]
Hm, the issue is that sending the trailers sends an `end stream`? Yet you don't see the the trailers in the dump at all?

I'd have expected the issue to be trailers with the end stream getting there before all of the data is received, but if you aren't seeing the trailers at all I'm confused.

Or maybe there is a timeout happening... 

This is all localhost when calling grpcurl? What size binary are you using so I can try to reproduce?

**Comment by russagit** [comment]
Correct, I see no trailer in the dump.
Yes, this is all localhost and my binary size to reproduce is 179834 bytes.
