### ISSUE TITLE
Missing git tag v0.14.0

### ISSUE THREAD

**Issue by fenollp** [tsloughter/grpcbox#69]
Compare git tags: https://github.com/tsloughter/grpcbox/tags 
with hex.pm releases: https://hex.pm/packages/grpcbox

**Comment by tsloughter** [comment]
Thanks, I'll get that figured out.

**Comment by KornelH** [comment]
Tag `0.12.0` is also missing from [Git](https://github.com/tsloughter/grpcbox/tags) however present in [hex.pm](https://hex.pm/packages/grpcbox). Was it tagged before and become removed or was never tagged on the first place?

Similarly some older versions are also not tagged like `0.6.0`, `0.1.1` and `0.1.0` but those are old indeed so that's ok.

**Comment by tsloughter** [comment]
Pushed them up and made a new release.
